export { default as Logo } from './assets/logo.svg'
export { default as Category } from './assets/category.svg'
export { default as Box } from './assets/box.svg'
export { default as Profile } from './assets/profile-2user.svg'
export { default as Trend } from './assets/trend-up.svg'
export { default as Discount } from './assets/discount-shape.svg'
export { default as Info } from './assets/info-circle.svg'
export { default as Bulb } from './assets/brightness-1.svg'
export { default as Moon } from './assets/moon 1.svg'
export { default as LogIn } from './assets/arrow-right.svg'
export { default as Settings } from './assets/setting-2.svg'
export { default as LogOut } from './assets/logout.svg'
export { default as Active } from './assets/Active.svg'
export { default as Search } from './assets/Icon - Search.svg'
export { default as Calendar } from './assets/trend-up.svg'
export { default as Notification } from './assets/solar_bell-outline.svg'